config/routes.rb
Rails.application.routes.draw do
  scope module: :personal_room do
    scope '/api', module: :api, defaults: { format: 'json' } do
      resources :users do
        get 'current' => 'users#current', on: :collection
        get 'count'   => 'users#count',   on: :collection
        post 'login_by_card/:card_number' => 'users#login_by_card', on: :collection

        put 'stop' => 'users#stop'
      end

      resources :cards do
        post  '/start'  => 'cards#start'
        put   '/stop'   => 'cards#stop'
      end

      resources :apps
    end
  end

  scope :personal_room do
    devise_for :users,
               controllers: {
                 omniauth_callbacks: 'personal_room/users/omniauth_callbacks'
               },
               class_name: 'PersonalRoom::User',
               skip: [:sessions, :registrations, :passwords]

    devise_scope :user do
      get 'logout' => 'devise/sessions#destroy', :as => :destroy_user_session
    end

    get '/' => 'personal_room/application#index', as: :personal_room_root
  end

  scope module: :front do
    get '/'         => 'home#index',      as: :homepage
    get 'login'     => 'home#login',      as: :login
    get 'place'     => 'place#index',     as: :place
    get 'services'  => 'services#index',  as: :services
    get 'contacts'  => 'contacts#index',  as: :contacts
  end

  root 'home_controller#index'
end

app/views/layouts/application.html.haml
!!! 5
%html(lang='ru')
  %head
    %title Антикафе «Фонтан», Новосибирск
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    = csrf_meta_tags
    = stylesheet_link_tag 'application', :media => 'all'
    <link href='https://fonts.googleapis.com/css?family=Russo+One&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
  %body
    #wrap
      %header
        %h1.ui.header
          %a{href: root_url} Фонтан
          .sub.header Антикафе

        .ui.four.item.menu
          %a.item{href: homepage_url, class: "#{current_page?(homepage_url) ? 'active' : '' }"} Главная
          %a.item{href: place_url, class: "#{current_page?(place_url) ? 'active' : '' }"} О месте
          %a.item{href: services_url, class: "#{current_page?(services_url) ? 'active' : '' }"} Услуги
          %a.item{href: contacts_url, class: "#{current_page?(contacts_url) ? 'active' : '' }"} Контакты

      #main
        = yield

      #push

    %footer
      .ui.container
        .ui.horizontal.segments
          .ui.segment
            .ui.list
              .item
                &copy; 2015 Антикафе «Фонтан»
              .item
                %a{href: login_url} В свою комнату
          .ui.segment
            .ui.list
              .item
                %i.fa.fa-clock-o
                %span 00.00-24.00, пон-вск
              .item
                %i.fa.fa-map-marker
                %a{href: 'https://2gis.ru/novosibirsk/search/%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D0%B2%D0%B8%D0%BD%D0%B0%201/geo/141373143518845/center/82.912359%2C55.040916'}
                  г. Новосибирск, ул. Державина 1
              .item
                %i.fa.fa-mobile
                %span +7 (913) 208-6998

app/views/layouts/personal_room.html.haml
!!!
%html(lang='ru' ng-app='fontan')
  %head
    %title Антикафе «Фонтан», Новосибирск

    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")

    = stylesheet_link_tag 'application', :media => 'all'
    = stylesheet_link_tag 'personal_room/application', media: 'all'
    = csrf_meta_tags
    :javascript
      window.config = {
        is_development:   '#{(Rails.env.production?)? 'false' : 'true' }',
        websockets_host:  '#{Rails.application.config.custom[:websockets_host]}',
        links: {
          logout: '#{destroy_user_session_url}',
          root: '#{personal_room_root_url}',
          mainSite: '#{root_url}'
        }
      }
  %body{'ng-controller' => 'MainCtl'}
    #wrap.ui.container
      #loading-block
        .loader-inner.pacman
          %div
          %div
          %div
          %div
      %header{'ng-include' => "'shared/header.html'"}

      #main
        %ui-view

      #push

    %footer{'ng-include' => "'shared/footer.html'"}

    = javascript_include_tag 'personal_room/application'